print("hello world")
print("[Damulrra]: pull from remote source modified by [thegreatestlater].")
print("[Damulrra]: make branch of BRN-001")
print("[thegreatestlater]: make branch of BRN-002.")
print("[thegreatestlater]: bugfix...")
print("-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+")
print("[Damulraa]: git_reset_test_0001")
print("[Damulraa]: git_reset_test_0002")
